/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Painel_Doacao;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Tiago Cunha
 */
public class Inserir_Doacoes extends javax.swing.JPanel {

    /**
     * Creates new form painel_consulta
     */
    public Inserir_Doacoes() {
        initComponents();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Niss = new javax.swing.JFormattedTextField();
        Valor = new javax.swing.JFormattedTextField();
        Quantidade = new javax.swing.JFormattedTextField();
        Tipo = new javax.swing.JFormattedTextField();
        Dia = new javax.swing.JFormattedTextField();
        Mes = new javax.swing.JFormattedTextField();
        Ano = new javax.swing.JFormattedTextField();
        Material = new javax.swing.JCheckBox();
        Dinheiro = new javax.swing.JCheckBox();
        Inserir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setOpaque(false);
        setLayout(null);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("NISS (Doador)");
        add(jLabel8);
        jLabel8.setBounds(170, 200, 90, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Tipo");
        add(jLabel10);
        jLabel10.setBounds(510, 250, 40, 30);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Quantidade");
        add(jLabel14);
        jLabel14.setBounds(360, 250, 80, 30);

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("Valor");
        add(jLabel17);
        jLabel17.setBounds(370, 290, 60, 30);

        jLabel48.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel48.setText("Doação");
        add(jLabel48);
        jLabel48.setBounds(170, 270, 60, 30);

        jLabel78.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel78.setText("Data");
        add(jLabel78);
        jLabel78.setBounds(170, 340, 70, 30);

        jLabel1.setText("  (dd-mm-aaaa)");
        add(jLabel1);
        jLabel1.setBounds(320, 370, 80, 20);

        Niss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NissActionPerformed(evt);
            }
        });
        add(Niss);
        Niss.setBounds(280, 200, 150, 30);

        Valor.setEnabled(false);
        add(Valor);
        Valor.setBounds(440, 290, 60, 30);

        Quantidade.setEnabled(false);
        Quantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuantidadeActionPerformed(evt);
            }
        });
        add(Quantidade);
        Quantidade.setBounds(440, 250, 60, 30);

        Tipo.setEnabled(false);
        add(Tipo);
        Tipo.setBounds(560, 250, 100, 30);
        add(Dia);
        Dia.setBounds(280, 340, 40, 30);
        add(Mes);
        Mes.setBounds(340, 340, 40, 30);
        add(Ano);
        Ano.setBounds(400, 340, 40, 30);

        Material.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Material.setText("Material");
        Material.setOpaque(false);
        Material.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                MaterialStateChanged(evt);
            }
        });
        Material.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MaterialMouseClicked(evt);
            }
        });
        Material.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                MaterialComponentShown(evt);
            }
        });
        Material.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaterialActionPerformed(evt);
            }
        });
        add(Material);
        Material.setBounds(280, 250, 110, 30);

        Dinheiro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Dinheiro.setText("Dinheiro");
        Dinheiro.setOpaque(false);
        Dinheiro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DinheiroMouseClicked(evt);
            }
        });
        Dinheiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DinheiroActionPerformed(evt);
            }
        });
        add(Dinheiro);
        Dinheiro.setBounds(280, 290, 110, 30);

        Inserir.setText("Inserir");
        Inserir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InserirMouseClicked(evt);
            }
        });
        Inserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InserirActionPerformed(evt);
            }
        });
        add(Inserir);
        Inserir.setBounds(690, 450, 80, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/987.jpg"))); // NOI18N
        add(jLabel2);
        jLabel2.setBounds(0, 0, 960, 610);
    }// </editor-fold>//GEN-END:initComponents

    private void NissActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NissActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NissActionPerformed

    private void QuantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuantidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_QuantidadeActionPerformed

    private void MaterialStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_MaterialStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_MaterialStateChanged

    private void MaterialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MaterialMouseClicked
        // TODO add your handling code here:
        if(Material.isSelected()){
            Quantidade.setEnabled(true);
            Tipo.setEnabled(true);
            Dinheiro.setEnabled(false);
        }else{
            Quantidade.setEnabled(false);
            Tipo.setEnabled(false);
            Dinheiro.setEnabled(true);
        }
    }//GEN-LAST:event_MaterialMouseClicked

    private void MaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaterialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MaterialActionPerformed

    private void DinheiroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DinheiroMouseClicked
        // TODO add your handling code here:
        if(Dinheiro.isSelected()){
            Valor.setEnabled(true);
            Material.setEnabled(false);
        }else{
            Valor.setEnabled(false);
            Material.setEnabled(true);     
        }
    }//GEN-LAST:event_DinheiroMouseClicked

    private void InserirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InserirMouseClicked
        // TODO add your handling code here:
        if (this.Niss.getText().equals("") || this.Dia.getText().equals("") || this.Mes.getText().equals("") || this.Ano.getText().equals("") || (!this.Material.isSelected() && !this.Dinheiro.isSelected())) {
            JOptionPane.showMessageDialog(null, "Preencha todos os campos!");
        }else{
            JOptionPane.showMessageDialog(null, "Inserido!");
            this.Niss.setText("");
            this.Dia.setText("");
            this.Mes.setText("");
            this.Ano.setText("");
            this.Dinheiro.setSelected(false);
            this.Material.setSelected(false);
            this.Quantidade.setText("");
            this.Tipo.setText("");
            this.Valor.setText("");
        }    
    }//GEN-LAST:event_InserirMouseClicked

    private void InserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InserirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InserirActionPerformed

    private void MaterialComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_MaterialComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_MaterialComponentShown

    private void DinheiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DinheiroActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_DinheiroActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField Ano;
    private javax.swing.JFormattedTextField Dia;
    private javax.swing.JCheckBox Dinheiro;
    private javax.swing.JButton Inserir;
    private javax.swing.JCheckBox Material;
    private javax.swing.JFormattedTextField Mes;
    private javax.swing.JFormattedTextField Niss;
    private javax.swing.JFormattedTextField Quantidade;
    private javax.swing.JFormattedTextField Tipo;
    private javax.swing.JFormattedTextField Valor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
