/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Painel_Doacao;

import javax.swing.JOptionPane;

/**
 *
 * @author Tiago Cunha
 */
public class Remover_Consultar_Doacoes extends javax.swing.JPanel {

    /**
     * Creates new form Remover
     */
    public Remover_Consultar_Doacoes() {
        initComponents();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Doacoes = new javax.swing.JList();
        Remover = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Niss = new javax.swing.JFormattedTextField();
        Valor = new javax.swing.JFormattedTextField();
        Quantidade = new javax.swing.JFormattedTextField();
        Tipo = new javax.swing.JFormattedTextField();
        Dia = new javax.swing.JFormattedTextField();
        Mes = new javax.swing.JFormattedTextField();
        Ano = new javax.swing.JFormattedTextField();
        Material = new javax.swing.JCheckBox();
        Dinheiro = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();

        setLayout(null);

        Doacoes.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5", "Item 1", "Item 2", "Item 3", "Item 4", "Item 5", "Item 1", "Item 2", "Item 3", "Item 4", "Item 5", "Item 1", "Item 2", "Item 3", "Item 4", "Item 5", "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(Doacoes);

        add(jScrollPane1);
        jScrollPane1.setBounds(30, 120, 140, 360);

        Remover.setText("Remover");
        Remover.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RemoverMouseClicked(evt);
            }
        });
        add(Remover);
        Remover.setBounds(30, 500, 140, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("NISS (Doador)");
        add(jLabel8);
        jLabel8.setBounds(260, 200, 90, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Tipo");
        add(jLabel10);
        jLabel10.setBounds(600, 250, 40, 30);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Quantidade");
        add(jLabel14);
        jLabel14.setBounds(450, 250, 80, 30);

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("Valor");
        add(jLabel17);
        jLabel17.setBounds(460, 290, 60, 30);

        jLabel48.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel48.setText("Doação");
        add(jLabel48);
        jLabel48.setBounds(260, 270, 60, 30);

        jLabel78.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel78.setText("Data");
        add(jLabel78);
        jLabel78.setBounds(260, 340, 70, 30);

        jLabel2.setText("  (dd-mm-aaaa)");
        add(jLabel2);
        jLabel2.setBounds(410, 370, 80, 20);

        Niss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NissActionPerformed(evt);
            }
        });
        add(Niss);
        Niss.setBounds(370, 200, 150, 30);

        Valor.setEnabled(false);
        add(Valor);
        Valor.setBounds(530, 290, 60, 30);

        Quantidade.setEnabled(false);
        Quantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuantidadeActionPerformed(evt);
            }
        });
        add(Quantidade);
        Quantidade.setBounds(530, 250, 60, 30);

        Tipo.setEnabled(false);
        add(Tipo);
        Tipo.setBounds(650, 250, 100, 30);
        add(Dia);
        Dia.setBounds(370, 340, 40, 30);
        add(Mes);
        Mes.setBounds(430, 340, 40, 30);
        add(Ano);
        Ano.setBounds(490, 340, 40, 30);

        Material.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Material.setText("Material");
        Material.setOpaque(false);
        Material.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                MaterialStateChanged(evt);
            }
        });
        Material.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MaterialMouseClicked(evt);
            }
        });
        Material.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaterialActionPerformed(evt);
            }
        });
        add(Material);
        Material.setBounds(370, 250, 110, 30);

        Dinheiro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Dinheiro.setText("Dinheiro");
        Dinheiro.setOpaque(false);
        Dinheiro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DinheiroMouseClicked(evt);
            }
        });
        add(Dinheiro);
        Dinheiro.setBounds(370, 290, 110, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/987.jpg"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(0, 0, 954, 608);
    }// </editor-fold>//GEN-END:initComponents

    private void RemoverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RemoverMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Removido!");
    }//GEN-LAST:event_RemoverMouseClicked

    private void NissActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NissActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NissActionPerformed

    private void QuantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuantidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_QuantidadeActionPerformed

    private void MaterialStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_MaterialStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_MaterialStateChanged

    private void MaterialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MaterialMouseClicked
        // TODO add your handling code here:
        if(Material.isSelected()){
            Quantidade.setEnabled(true);
            Tipo.setEnabled(true);
            Dinheiro.setEnabled(false);
        }else{
            Quantidade.setEnabled(false);
            Tipo.setEnabled(false);
            Dinheiro.setEnabled(true);
        }
    }//GEN-LAST:event_MaterialMouseClicked

    private void MaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaterialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MaterialActionPerformed

    private void DinheiroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DinheiroMouseClicked
        // TODO add your handling code here:
        if(Dinheiro.isSelected()){
            Valor.setEnabled(true);
            Material.setEnabled(false);
        }else{
            Valor.setEnabled(false);
            Material.setEnabled(true);
        }
    }//GEN-LAST:event_DinheiroMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField Ano;
    private javax.swing.JFormattedTextField Dia;
    private javax.swing.JCheckBox Dinheiro;
    private javax.swing.JList Doacoes;
    private javax.swing.JCheckBox Material;
    private javax.swing.JFormattedTextField Mes;
    private javax.swing.JFormattedTextField Niss;
    private javax.swing.JFormattedTextField Quantidade;
    private javax.swing.JButton Remover;
    private javax.swing.JFormattedTextField Tipo;
    private javax.swing.JFormattedTextField Valor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
