/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Painel_Voluntario;

import javax.swing.JOptionPane;
import java.lang.*;

/**
 *
 * @author Tiago Cunha
 */
public class Inserir_Voluntarios extends javax.swing.JPanel {

    /**
     * Creates new form Inserir
     */
    public Inserir_Voluntarios() {
        initComponents();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel34 = new javax.swing.JLabel();
        Nome = new javax.swing.JFormattedTextField();
        Idade = new javax.swing.JFormattedTextField();
        jLabel36 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        Nacionalidade = new javax.swing.JFormattedTextField();
        Niss = new javax.swing.JFormattedTextField();
        jLabel41 = new javax.swing.JLabel();
        Nif = new javax.swing.JFormattedTextField();
        jLabel40 = new javax.swing.JLabel();
        Telefone = new javax.swing.JFormattedTextField();
        jLabel44 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        Telemovel = new javax.swing.JFormattedTextField();
        jLabel43 = new javax.swing.JLabel();
        Feminino = new javax.swing.JCheckBox();
        Masculino = new javax.swing.JCheckBox();
        Morada = new javax.swing.JFormattedTextField();
        jLabel38 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        Cod_Postal = new javax.swing.JFormattedTextField();
        jLabel39 = new javax.swing.JLabel();
        Localidade = new javax.swing.JFormattedTextField();
        Email = new javax.swing.JFormattedTextField();
        jLabel45 = new javax.swing.JLabel();
        Inserir = new javax.swing.JButton();
        Equipa = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(954, 608));
        setMinimumSize(new java.awt.Dimension(954, 608));
        setLayout(null);

        jLabel34.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel34.setText("Nome");
        add(jLabel34);
        jLabel34.setBounds(170, 160, 50, 30);
        add(Nome);
        Nome.setBounds(260, 160, 380, 30);

        Idade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdadeActionPerformed(evt);
            }
        });
        add(Idade);
        Idade.setBounds(260, 210, 100, 30);

        jLabel36.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel36.setText("Idade");
        add(jLabel36);
        jLabel36.setBounds(170, 210, 130, 30);

        jLabel42.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel42.setText("Nacionalidade");
        add(jLabel42);
        jLabel42.setBounds(400, 210, 90, 30);
        add(Nacionalidade);
        Nacionalidade.setBounds(500, 210, 140, 30);
        add(Niss);
        Niss.setBounds(540, 260, 100, 30);

        jLabel41.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel41.setText("NISS");
        add(jLabel41);
        jLabel41.setBounds(500, 260, 29, 30);
        add(Nif);
        Nif.setBounds(400, 260, 90, 30);

        jLabel40.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel40.setText("NIF");
        add(jLabel40);
        jLabel40.setBounds(370, 260, 30, 30);
        add(Telefone);
        Telefone.setBounds(260, 260, 100, 30);

        jLabel44.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel44.setText("Telefone");
        add(jLabel44);
        jLabel44.setBounds(170, 260, 70, 30);

        jLabel35.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel35.setText("Telemovel");
        add(jLabel35);
        jLabel35.setBounds(170, 310, 80, 30);
        add(Telemovel);
        Telemovel.setBounds(260, 310, 100, 30);

        jLabel43.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel43.setText("Género");
        add(jLabel43);
        jLabel43.setBounds(380, 310, 50, 30);

        Feminino.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Feminino.setText("Feminino");
        Feminino.setOpaque(false);
        Feminino.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FemininoMouseClicked(evt);
            }
        });
        add(Feminino);
        Feminino.setBounds(430, 290, 90, 30);

        Masculino.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Masculino.setText("Masculino");
        Masculino.setOpaque(false);
        Masculino.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MasculinoMouseClicked(evt);
            }
        });
        add(Masculino);
        Masculino.setBounds(430, 330, 100, 30);
        add(Morada);
        Morada.setBounds(260, 360, 380, 30);

        jLabel38.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel38.setText("Morada");
        add(jLabel38);
        jLabel38.setBounds(170, 360, 70, 30);

        jLabel37.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel37.setText("Código-Postal");
        add(jLabel37);
        jLabel37.setBounds(260, 400, 100, 30);
        add(Cod_Postal);
        Cod_Postal.setBounds(350, 400, 110, 30);

        jLabel39.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel39.setText("Localidade");
        add(jLabel39);
        jLabel39.setBounds(470, 400, 100, 30);
        add(Localidade);
        Localidade.setBounds(540, 400, 100, 30);
        add(Email);
        Email.setBounds(260, 440, 380, 30);

        jLabel45.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel45.setText("E-mail");
        add(jLabel45);
        jLabel45.setBounds(170, 440, 60, 30);

        Inserir.setText("Inserir");
        Inserir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InserirMouseClicked(evt);
            }
        });
        Inserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InserirActionPerformed(evt);
            }
        });
        add(Inserir);
        Inserir.setBounds(690, 480, 80, 30);

        Equipa.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Equipa", "Item 2", "Item 3", "Item 4" }));
        Equipa.setToolTipText("Equipa");
        add(Equipa);
        Equipa.setBounds(520, 310, 120, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/987.jpg"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(0, 0, 954, 608);
    }// </editor-fold>//GEN-END:initComponents

    private void FemininoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FemininoMouseClicked
        // TODO add your handling code here:
        if(Feminino.isSelected()){
            Masculino.setEnabled(false);
        }else{
            Masculino.setEnabled(true);;
        }
    }//GEN-LAST:event_FemininoMouseClicked

    private void MasculinoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MasculinoMouseClicked
        // TODO add your handling code here:
        if(Masculino.isSelected()){
            Feminino.setEnabled(false);
        }else{
            Feminino.setEnabled(true);;
        }
    }//GEN-LAST:event_MasculinoMouseClicked

    private void InserirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InserirMouseClicked
        // TODO add your handling code here:
                
        if (this.Idade.getText().equals("") || this.Cod_Postal.getText().equals("") || this.Niss.getText().equals("") || 
            this.Nome.getText().equals("") || this.Nacionalidade.getText().equals("") || this.Telefone.getText().equals("") || this.Nif.getText().equals("") ||
            this.Telemovel.getText().equals("") || this.Morada.getText().equals("") || this.Localidade.getText().equals("") || 
            this.Email.getText().equals("") || (!this.Feminino.isSelected() && !this.Masculino.isSelected())) {
            JOptionPane.showMessageDialog(null, "Preencha todos os campos!");
        }else{
            String i = this.Idade.getText();
            int idd = Integer.parseInt(i);
            
            if (idd < 16 ){
                JOptionPane.showMessageDialog(null, "Voluntário < 16 anos!");
                this.Idade.setText(null);
            }else{
            JOptionPane.showMessageDialog(null, "Inserido!");
            this.Niss.setText("");
            this.Nome.setText("");
            this.Nacionalidade.setText("");
            this.Telefone.setText("");
            this.Nif.setText("");
            this.Telemovel.setText("");
            this.Morada.setText("");
            this.Localidade.setText("");
            this.Email.setText("");
            this.Cod_Postal.setText("");
            this.Idade.setText("");
            this.Feminino.setSelected(false);
            this.Masculino.setSelected(false);
            }    
        }
    }//GEN-LAST:event_InserirMouseClicked

    private void InserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InserirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InserirActionPerformed

    private void IdadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IdadeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField Cod_Postal;
    private javax.swing.JFormattedTextField Email;
    private javax.swing.JComboBox Equipa;
    private javax.swing.JCheckBox Feminino;
    private javax.swing.JFormattedTextField Idade;
    private javax.swing.JButton Inserir;
    private javax.swing.JFormattedTextField Localidade;
    private javax.swing.JCheckBox Masculino;
    private javax.swing.JFormattedTextField Morada;
    private javax.swing.JFormattedTextField Nacionalidade;
    private javax.swing.JFormattedTextField Nif;
    private javax.swing.JFormattedTextField Niss;
    private javax.swing.JFormattedTextField Nome;
    private javax.swing.JFormattedTextField Telefone;
    private javax.swing.JFormattedTextField Telemovel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    // End of variables declaration//GEN-END:variables
}
