/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Painel_Voluntario;

import javax.swing.JOptionPane;

/**
 *
 * @author Tiago Cunha
 */
public class Remover_Consultar_Voluntarios extends javax.swing.JPanel {

    /**
     * Creates new form Remover_Consultar_Voluntarios
     */
    public Remover_Consultar_Voluntarios() {
        initComponents();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel34 = new javax.swing.JLabel();
        Nome = new javax.swing.JFormattedTextField();
        Idade = new javax.swing.JFormattedTextField();
        jLabel36 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        Nacionalidade = new javax.swing.JFormattedTextField();
        Niss = new javax.swing.JFormattedTextField();
        jLabel41 = new javax.swing.JLabel();
        Nif = new javax.swing.JFormattedTextField();
        Telefone = new javax.swing.JFormattedTextField();
        jLabel44 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        Feminino = new javax.swing.JCheckBox();
        Masculino = new javax.swing.JCheckBox();
        Telemovel = new javax.swing.JFormattedTextField();
        jLabel35 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        Morada = new javax.swing.JFormattedTextField();
        Cod_Postal = new javax.swing.JFormattedTextField();
        jLabel37 = new javax.swing.JLabel();
        Localidade = new javax.swing.JFormattedTextField();
        jLabel39 = new javax.swing.JLabel();
        Email = new javax.swing.JFormattedTextField();
        jLabel45 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Voluntarios = new javax.swing.JList();
        Remover = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Equipa = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(954, 608));
        setMinimumSize(new java.awt.Dimension(954, 608));
        setLayout(null);

        jLabel34.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel34.setText("Nome");
        add(jLabel34);
        jLabel34.setBounds(270, 160, 50, 30);
        add(Nome);
        Nome.setBounds(360, 160, 380, 30);
        add(Idade);
        Idade.setBounds(360, 210, 100, 30);

        jLabel36.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel36.setText("Idade");
        add(jLabel36);
        jLabel36.setBounds(270, 210, 130, 30);

        jLabel42.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel42.setText("Nacionalidade");
        add(jLabel42);
        jLabel42.setBounds(500, 210, 90, 30);
        add(Nacionalidade);
        Nacionalidade.setBounds(600, 210, 140, 30);
        add(Niss);
        Niss.setBounds(640, 260, 100, 30);

        jLabel41.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel41.setText("NISS");
        add(jLabel41);
        jLabel41.setBounds(600, 260, 29, 30);
        add(Nif);
        Nif.setBounds(500, 260, 90, 30);
        add(Telefone);
        Telefone.setBounds(360, 260, 100, 30);

        jLabel44.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel44.setText("Telefone");
        add(jLabel44);
        jLabel44.setBounds(270, 260, 70, 30);

        jLabel40.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel40.setText("NIF");
        add(jLabel40);
        jLabel40.setBounds(470, 260, 30, 30);

        jLabel43.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel43.setText("Género");
        add(jLabel43);
        jLabel43.setBounds(480, 310, 50, 30);

        Feminino.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Feminino.setText("Feminino");
        Feminino.setOpaque(false);
        Feminino.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FemininoMouseClicked(evt);
            }
        });
        add(Feminino);
        Feminino.setBounds(530, 290, 90, 30);

        Masculino.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Masculino.setText("Masculino");
        Masculino.setOpaque(false);
        Masculino.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MasculinoMouseClicked(evt);
            }
        });
        add(Masculino);
        Masculino.setBounds(530, 330, 100, 30);
        add(Telemovel);
        Telemovel.setBounds(360, 310, 100, 30);

        jLabel35.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel35.setText("Telemovel");
        add(jLabel35);
        jLabel35.setBounds(270, 310, 80, 30);

        jLabel38.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel38.setText("Morada");
        add(jLabel38);
        jLabel38.setBounds(270, 360, 70, 30);
        add(Morada);
        Morada.setBounds(360, 360, 380, 30);
        add(Cod_Postal);
        Cod_Postal.setBounds(450, 400, 110, 30);

        jLabel37.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel37.setText("Código-Postal");
        add(jLabel37);
        jLabel37.setBounds(360, 400, 100, 30);
        add(Localidade);
        Localidade.setBounds(640, 400, 100, 30);

        jLabel39.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel39.setText("Localidade");
        add(jLabel39);
        jLabel39.setBounds(570, 400, 100, 30);
        add(Email);
        Email.setBounds(360, 440, 200, 30);

        jLabel45.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel45.setText("E-mail");
        add(jLabel45);
        jLabel45.setBounds(270, 440, 60, 30);

        Voluntarios.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(Voluntarios);

        add(jScrollPane1);
        jScrollPane1.setBounds(60, 160, 130, 270);

        Remover.setText("Remover");
        Remover.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RemoverMouseClicked(evt);
            }
        });
        add(Remover);
        Remover.setBounds(60, 440, 130, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Equipa");
        add(jLabel1);
        jLabel1.setBounds(570, 440, 50, 30);

        Equipa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EquipaActionPerformed(evt);
            }
        });
        add(Equipa);
        Equipa.setBounds(639, 440, 100, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/987.jpg"))); // NOI18N
        add(jLabel2);
        jLabel2.setBounds(0, 0, 954, 608);
    }// </editor-fold>//GEN-END:initComponents

    private void FemininoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FemininoMouseClicked
        // TODO add your handling code here:
        if(Feminino.isSelected()){
            Masculino.setEnabled(false);
        }else{
            Masculino.setEnabled(true);;
        }
    }//GEN-LAST:event_FemininoMouseClicked

    private void MasculinoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MasculinoMouseClicked
        // TODO add your handling code here:
        if(Masculino.isSelected()){
            Feminino.setEnabled(false);
        }else{
            Feminino.setEnabled(true);;
        }
    }//GEN-LAST:event_MasculinoMouseClicked

    private void RemoverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RemoverMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Removido com Sucesso!");
    }//GEN-LAST:event_RemoverMouseClicked

    private void EquipaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EquipaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EquipaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField Cod_Postal;
    private javax.swing.JFormattedTextField Email;
    private javax.swing.JFormattedTextField Equipa;
    private javax.swing.JCheckBox Feminino;
    private javax.swing.JFormattedTextField Idade;
    private javax.swing.JFormattedTextField Localidade;
    private javax.swing.JCheckBox Masculino;
    private javax.swing.JFormattedTextField Morada;
    private javax.swing.JFormattedTextField Nacionalidade;
    private javax.swing.JFormattedTextField Nif;
    private javax.swing.JFormattedTextField Niss;
    private javax.swing.JFormattedTextField Nome;
    private javax.swing.JButton Remover;
    private javax.swing.JFormattedTextField Telefone;
    private javax.swing.JFormattedTextField Telemovel;
    private javax.swing.JList Voluntarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
