/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Habitat;

import java.awt.Color;
import java.awt.Font;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import Painel_Doacao.Inserir_Doacoes;

/**
 *
 * @author Tiago Cunha
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NISS_Login = new javax.swing.JFormattedTextField();
        Login = new javax.swing.JButton();
        Fundo_Login = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(237, 404));
        setResizable(false);
        getContentPane().setLayout(null);

        NISS_Login.setForeground(new java.awt.Color(204, 204, 204));
        NISS_Login.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        NISS_Login.setText("NISS");
        NISS_Login.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        NISS_Login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NISS_LoginMouseClicked(evt);
            }
        });
        NISS_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NISS_LoginActionPerformed(evt);
            }
        });
        getContentPane().add(NISS_Login);
        NISS_Login.setBounds(40, 230, 150, 30);

        Login.setText("Login");
        Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginActionPerformed(evt);
            }
        });
        getContentPane().add(Login);
        Login.setBounds(60, 280, 110, 30);

        Fundo_Login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Login.jpg"))); // NOI18N
        getContentPane().add(Fundo_Login);
        Fundo_Login.setBounds(0, 0, 237, 404);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginActionPerformed
        // TODO add your handling code here:
        if (NISS_Login.getText().equals("1234")){
            //JOptionPane.showMessageDialog(null, "Acesso Garantido!");
            new proxMenu().setVisible(true);
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(null, "Dados incorretos!");
            
            //this.NISS.setText("");
            Font f = new Font("Tahoma",Font.PLAIN,11);
            this.NISS_Login.setFont(f);
            this.NISS_Login.setForeground(Color.gray);
            this.NISS_Login.setText("NISS");
            
        }
    }//GEN-LAST:event_LoginActionPerformed

    private void NISS_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NISS_LoginActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_NISS_LoginActionPerformed

    private void NISS_LoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NISS_LoginMouseClicked
        // TODO add your handling code here:
        this.NISS_Login.setForeground(Color.black);
        this.NISS_Login.setText("");
        Font f = new Font("Wingdings 3",Font.BOLD,12);
        this.NISS_Login.setFont(f);
    }//GEN-LAST:event_NISS_LoginMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Login().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fundo_Login;
    private javax.swing.JButton Login;
    private javax.swing.JFormattedTextField NISS_Login;
    // End of variables declaration//GEN-END:variables
}
