/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Habitat;

import java.awt.Container;
import javax.swing.JPanel;
import Painel_Administrador.Inserir_Funcionario;
import Painel_Administrador.Remover_Consultar_Funcionario;
import Painel_Candidatura.Inserir_Candidatura;
import Painel_Candidatura.Remover_Consultar_Candidatura;
import Painel_Doador.Inserir_Doador;
import Painel_Doador.Remover_Consultar_Doador;
import Painel_Familia.Inserir_Familia;
import Painel_Familia.Membro_Familia;
import Painel_Familia.Remover_Consultar_Familia;
import Painel_Projecto.Inserir_Projecto;
import Painel_Projecto.Remover_Consultar_Projectos;
import Painel_Tarefa.Inserir_Tarefa;
import Painel_Tarefa.Remover_Consultar_Tarefa;
import Painel_Voluntario.Inserir_Voluntarios;
import Painel_Voluntario.Remover_Consultar_Voluntarios;
import Painel_Armazem.Consultar;
import Painel_Armazem.Inserir;
import Painel_Doacao.Inserir_Doacoes;
import Painel_Doacao.Remover_Consultar_Doacoes;

/**
 *
 * @author Tiago Cunha
 */
public class proxMenu extends javax.swing.JFrame {

    /**
     * Creates new form proxMenu
     */
    
    private Container contain;
    
    public proxMenu() {
        initComponents();
    }

    

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imagem_fundo = new javax.swing.JPanel();
        welcomebutton = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Habitat = new javax.swing.JMenuBar();
        Menu_Doacao = new javax.swing.JMenu();
        Inserir_Doacao = new javax.swing.JMenuItem();
        Remover_Consultar_Doacao = new javax.swing.JMenuItem();
        Menu_Doador = new javax.swing.JMenu();
        Inserir_Doador = new javax.swing.JMenuItem();
        Remover_Consultar_Doador = new javax.swing.JMenuItem();
        Menu_Voluntario = new javax.swing.JMenu();
        Inserir_Voluntario = new javax.swing.JMenuItem();
        Remover_Consultar_Voluntario = new javax.swing.JMenuItem();
        Menu_Projecto = new javax.swing.JMenu();
        Inserir_Projecto = new javax.swing.JMenuItem();
        Remover_Consultar_Projecto = new javax.swing.JMenuItem();
        Menu_Tarefa = new javax.swing.JMenu();
        Inserir_Tarefa = new javax.swing.JMenuItem();
        Remover_Consultar_Tarefa = new javax.swing.JMenuItem();
        Menu_Armazém = new javax.swing.JMenu();
        Inserir_Armazem = new javax.swing.JMenuItem();
        Remover_Consultar_Armazem = new javax.swing.JMenuItem();
        Menu_Familia = new javax.swing.JMenu();
        Inserir_Familia = new javax.swing.JMenuItem();
        Inserir_Membro_Familia = new javax.swing.JMenuItem();
        Remover_Consultar_Familia = new javax.swing.JMenuItem();
        Menu_Candidatura = new javax.swing.JMenu();
        Inserir_Candidatura = new javax.swing.JMenuItem();
        Remover_Consultar_Candidatura = new javax.swing.JMenuItem();
        Menu_Admin = new javax.swing.JMenu();
        Inserir_Admin = new javax.swing.JMenuItem();
        Remover_Consultar_Admin = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Habitat");
        setMinimumSize(new java.awt.Dimension(954, 608));
        setResizable(false);

        imagem_fundo.setLayout(null);

        welcomebutton.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        welcomebutton.setText("Bem-Vindo ");
        imagem_fundo.add(welcomebutton);
        welcomebutton.setBounds(60, 150, 330, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/987.jpg"))); // NOI18N
        imagem_fundo.add(jLabel1);
        jLabel1.setBounds(0, 0, 960, 600);

        getContentPane().add(imagem_fundo, java.awt.BorderLayout.CENTER);

        Menu_Doacao.setText("Doações");
        Menu_Doacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_DoacaoActionPerformed(evt);
            }
        });

        Inserir_Doacao.setText("Inserir");
        Inserir_Doacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Inserir_DoacaoActionPerformed(evt);
            }
        });
        Menu_Doacao.add(Inserir_Doacao);

        Remover_Consultar_Doacao.setText("Remover/Consultar");
        Remover_Consultar_Doacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Remover_Consultar_DoacaoActionPerformed(evt);
            }
        });
        Menu_Doacao.add(Remover_Consultar_Doacao);

        Habitat.add(Menu_Doacao);

        Menu_Doador.setText("Doador");

        Inserir_Doador.setText("Inserir");
        Inserir_Doador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Inserir_DoadorActionPerformed(evt);
            }
        });
        Menu_Doador.add(Inserir_Doador);

        Remover_Consultar_Doador.setText("Remover/Consultar");
        Remover_Consultar_Doador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Remover_Consultar_DoadorActionPerformed(evt);
            }
        });
        Menu_Doador.add(Remover_Consultar_Doador);

        Habitat.add(Menu_Doador);

        Menu_Voluntario.setText("Voluntários");

        Inserir_Voluntario.setText("Inserir");
        Inserir_Voluntario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Inserir_VoluntarioActionPerformed(evt);
            }
        });
        Menu_Voluntario.add(Inserir_Voluntario);

        Remover_Consultar_Voluntario.setText("Remover/Consultar");
        Remover_Consultar_Voluntario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Remover_Consultar_VoluntarioMouseClicked(evt);
            }
        });
        Remover_Consultar_Voluntario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Remover_Consultar_VoluntarioActionPerformed(evt);
            }
        });
        Menu_Voluntario.add(Remover_Consultar_Voluntario);

        Habitat.add(Menu_Voluntario);

        Menu_Projecto.setText("Projectos");

        Inserir_Projecto.setText("Inserir");
        Inserir_Projecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Inserir_ProjectoActionPerformed(evt);
            }
        });
        Menu_Projecto.add(Inserir_Projecto);

        Remover_Consultar_Projecto.setText("Remover/Consultar");
        Remover_Consultar_Projecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Remover_Consultar_ProjectoActionPerformed(evt);
            }
        });
        Menu_Projecto.add(Remover_Consultar_Projecto);

        Habitat.add(Menu_Projecto);

        Menu_Tarefa.setText("Tarefa");

        Inserir_Tarefa.setText("Inserir");
        Inserir_Tarefa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Inserir_TarefaActionPerformed(evt);
            }
        });
        Menu_Tarefa.add(Inserir_Tarefa);

        Remover_Consultar_Tarefa.setText("Remover/Consultar");
        Remover_Consultar_Tarefa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Remover_Consultar_TarefaActionPerformed(evt);
            }
        });
        Menu_Tarefa.add(Remover_Consultar_Tarefa);

        Habitat.add(Menu_Tarefa);

        Menu_Armazém.setText("Armazém");

        Inserir_Armazem.setText("Inserir");
        Inserir_Armazem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Inserir_ArmazemActionPerformed(evt);
            }
        });
        Menu_Armazém.add(Inserir_Armazem);

        Remover_Consultar_Armazem.setText("Consultar");
        Remover_Consultar_Armazem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Remover_Consultar_ArmazemActionPerformed(evt);
            }
        });
        Menu_Armazém.add(Remover_Consultar_Armazem);

        Habitat.add(Menu_Armazém);

        Menu_Familia.setText("Familia");

        Inserir_Familia.setText("Inserir");
        Inserir_Familia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Inserir_FamiliaActionPerformed(evt);
            }
        });
        Menu_Familia.add(Inserir_Familia);

        Inserir_Membro_Familia.setText("Inserir Membro");
        Inserir_Membro_Familia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Inserir_Membro_FamiliaActionPerformed(evt);
            }
        });
        Menu_Familia.add(Inserir_Membro_Familia);

        Remover_Consultar_Familia.setText("Remover/Consultar");
        Remover_Consultar_Familia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Remover_Consultar_FamiliaActionPerformed(evt);
            }
        });
        Menu_Familia.add(Remover_Consultar_Familia);

        Habitat.add(Menu_Familia);

        Menu_Candidatura.setText("Candidaturas");

        Inserir_Candidatura.setText("Inserir");
        Inserir_Candidatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Inserir_CandidaturaActionPerformed(evt);
            }
        });
        Menu_Candidatura.add(Inserir_Candidatura);

        Remover_Consultar_Candidatura.setText("Remover/Consultar");
        Remover_Consultar_Candidatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Remover_Consultar_CandidaturaActionPerformed(evt);
            }
        });
        Menu_Candidatura.add(Remover_Consultar_Candidatura);

        Habitat.add(Menu_Candidatura);

        Menu_Admin.setText("Admin");

        Inserir_Admin.setText("Inserir");
        Inserir_Admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Inserir_AdminActionPerformed(evt);
            }
        });
        Menu_Admin.add(Inserir_Admin);

        Remover_Consultar_Admin.setText("Remover/Consultar");
        Remover_Consultar_Admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Remover_Consultar_AdminActionPerformed(evt);
            }
        });
        Menu_Admin.add(Remover_Consultar_Admin);

        Habitat.add(Menu_Admin);

        jMenu1.setText("Opções");

        jMenuItem1.setText("HomePage");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Sair");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        Habitat.add(jMenu1);

        setJMenuBar(Habitat);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Inserir_DoacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Inserir_DoacaoActionPerformed
        // TODO add your handling code here:
        JPanel inserir = new Inserir_Doacoes();
        
        this.getContentPane().removeAll();
        this.getContentPane().add(inserir);
        this.validate();
    }//GEN-LAST:event_Inserir_DoacaoActionPerformed

    private void Menu_DoacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_DoacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Menu_DoacaoActionPerformed

    private void Remover_Consultar_DoacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Remover_Consultar_DoacaoActionPerformed
        // TODO add your handling code here:
        JPanel remover = new Remover_Consultar_Doacoes();
        
        this.getContentPane().removeAll();
        this.getContentPane().add(remover);
        this.validate();
    }//GEN-LAST:event_Remover_Consultar_DoacaoActionPerformed

    private void Remover_Consultar_AdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Remover_Consultar_AdminActionPerformed
        // TODO add your handling code here:
        JPanel remover = new Remover_Consultar_Funcionario();
        
        this.getContentPane().removeAll();
        this.getContentPane().add(remover);
        this.validate();
    }//GEN-LAST:event_Remover_Consultar_AdminActionPerformed

    private void Inserir_ProjectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Inserir_ProjectoActionPerformed
        // TODO add your handling code here:
        JPanel inserir = new Inserir_Projecto();
        
        this.getContentPane().removeAll();
        this.getContentPane().add(inserir);
        this.validate();
    }//GEN-LAST:event_Inserir_ProjectoActionPerformed

    private void Remover_Consultar_ProjectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Remover_Consultar_ProjectoActionPerformed
        // TODO add your handling code here:
        JPanel remover = new Remover_Consultar_Projectos();
        
        this.getContentPane().removeAll();
        this.getContentPane().add(remover);
        this.validate();
    }//GEN-LAST:event_Remover_Consultar_ProjectoActionPerformed

    private void Inserir_DoadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Inserir_DoadorActionPerformed
        // TODO add your handling code here:
        JPanel inserir = new Inserir_Doador();
        
        this.getContentPane().removeAll();
        this.getContentPane().add(inserir);
        this.validate();
    }//GEN-LAST:event_Inserir_DoadorActionPerformed

    private void Remover_Consultar_DoadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Remover_Consultar_DoadorActionPerformed
        // TODO add your handling code here:
        JPanel remover = new Remover_Consultar_Doador();
        
        this.getContentPane().removeAll();
        this.getContentPane().add(remover);
        this.validate();
    }//GEN-LAST:event_Remover_Consultar_DoadorActionPerformed

    private void Inserir_VoluntarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Inserir_VoluntarioActionPerformed
        // TODO add your handling code here:
        JPanel inserir = new Inserir_Voluntarios();
        
        this.getContentPane().removeAll();
        this.getContentPane().add(inserir);
        this.validate();
    }//GEN-LAST:event_Inserir_VoluntarioActionPerformed

    private void Remover_Consultar_VoluntarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Remover_Consultar_VoluntarioActionPerformed
        // TODO add your handling code here:
        JPanel remover = new Remover_Consultar_Voluntarios();
        
        this.getContentPane().removeAll();
        this.getContentPane().add(remover);
        this.validate();
    }//GEN-LAST:event_Remover_Consultar_VoluntarioActionPerformed

    private void Inserir_TarefaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Inserir_TarefaActionPerformed
        // TODO add your handling code here:
        JPanel inserir = new Inserir_Tarefa();
        
        this.getContentPane().removeAll();
        this.getContentPane().add(inserir);
        this.validate();
    }//GEN-LAST:event_Inserir_TarefaActionPerformed

    private void Remover_Consultar_TarefaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Remover_Consultar_TarefaActionPerformed
        // TODO add your handling code here:
        JPanel remover = new Remover_Consultar_Tarefa();
        
        this.getContentPane().removeAll();
        this.getContentPane().add(remover);
        this.validate();
    }//GEN-LAST:event_Remover_Consultar_TarefaActionPerformed

    private void Remover_Consultar_ArmazemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Remover_Consultar_ArmazemActionPerformed
        // TODO add your handling code here:
        JPanel consulta = new Consultar();
        
        this.getContentPane().removeAll();
        this.getContentPane().add(consulta);
        this.validate();
    }//GEN-LAST:event_Remover_Consultar_ArmazemActionPerformed

    private void Inserir_AdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Inserir_AdminActionPerformed
        // TODO add your handling code here:
        JPanel inserir = new Inserir_Funcionario();
        
        this.getContentPane().removeAll();
        this.getContentPane().add(inserir);
        this.validate();
    }//GEN-LAST:event_Inserir_AdminActionPerformed

    private void Inserir_FamiliaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Inserir_FamiliaActionPerformed
        // TODO add your handling code here:
        JPanel inserir = new Inserir_Familia();
        
        this.getContentPane().removeAll();
        this.getContentPane().add(inserir);
        this.validate();
    }//GEN-LAST:event_Inserir_FamiliaActionPerformed

    private void Remover_Consultar_FamiliaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Remover_Consultar_FamiliaActionPerformed
        // TODO add your handling code here:
        JPanel remover = new Remover_Consultar_Familia();
        
        this.getContentPane().removeAll();
        this.getContentPane().add(remover);
        this.validate();
    }//GEN-LAST:event_Remover_Consultar_FamiliaActionPerformed

    private void Remover_Consultar_VoluntarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Remover_Consultar_VoluntarioMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Remover_Consultar_VoluntarioMouseClicked

    private void Inserir_Membro_FamiliaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Inserir_Membro_FamiliaActionPerformed
        // TODO add your handling code here:
        JPanel membro = new Membro_Familia();
        
        this.getContentPane().removeAll();
        this.getContentPane().add(membro);
        this.validate();
    }//GEN-LAST:event_Inserir_Membro_FamiliaActionPerformed

    private void Inserir_CandidaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Inserir_CandidaturaActionPerformed
        // TODO add your handling code here:
        JPanel inserir = new Inserir_Candidatura();
        
        this.getContentPane().removeAll();
        this.getContentPane().add(inserir);
        this.validate();
    }//GEN-LAST:event_Inserir_CandidaturaActionPerformed

    private void Remover_Consultar_CandidaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Remover_Consultar_CandidaturaActionPerformed
        // TODO add your handling code here:
        JPanel remover = new Remover_Consultar_Candidatura();
        
        this.getContentPane().removeAll();
        this.getContentPane().add(remover);
        this.validate();
    }//GEN-LAST:event_Remover_Consultar_CandidaturaActionPerformed

    private void Inserir_ArmazemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Inserir_ArmazemActionPerformed
        // TODO add your handling code here:
        JPanel inserir = new Inserir();
        
        this.getContentPane().removeAll();
        this.getContentPane().add(inserir);
        this.validate();
    }//GEN-LAST:event_Inserir_ArmazemActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        JPanel home = new Home();
        
        this.getContentPane().removeAll();
        this.getContentPane().add(home);
        this.validate();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new proxMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar Habitat;
    private javax.swing.JMenuItem Inserir_Admin;
    private javax.swing.JMenuItem Inserir_Armazem;
    private javax.swing.JMenuItem Inserir_Candidatura;
    private javax.swing.JMenuItem Inserir_Doacao;
    private javax.swing.JMenuItem Inserir_Doador;
    private javax.swing.JMenuItem Inserir_Familia;
    private javax.swing.JMenuItem Inserir_Membro_Familia;
    private javax.swing.JMenuItem Inserir_Projecto;
    private javax.swing.JMenuItem Inserir_Tarefa;
    private javax.swing.JMenuItem Inserir_Voluntario;
    private javax.swing.JMenu Menu_Admin;
    private javax.swing.JMenu Menu_Armazém;
    private javax.swing.JMenu Menu_Candidatura;
    private javax.swing.JMenu Menu_Doacao;
    private javax.swing.JMenu Menu_Doador;
    private javax.swing.JMenu Menu_Familia;
    private javax.swing.JMenu Menu_Projecto;
    private javax.swing.JMenu Menu_Tarefa;
    private javax.swing.JMenu Menu_Voluntario;
    private javax.swing.JMenuItem Remover_Consultar_Admin;
    private javax.swing.JMenuItem Remover_Consultar_Armazem;
    private javax.swing.JMenuItem Remover_Consultar_Candidatura;
    private javax.swing.JMenuItem Remover_Consultar_Doacao;
    private javax.swing.JMenuItem Remover_Consultar_Doador;
    private javax.swing.JMenuItem Remover_Consultar_Familia;
    private javax.swing.JMenuItem Remover_Consultar_Projecto;
    private javax.swing.JMenuItem Remover_Consultar_Tarefa;
    private javax.swing.JMenuItem Remover_Consultar_Voluntario;
    private javax.swing.JPanel imagem_fundo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JLabel welcomebutton;
    // End of variables declaration//GEN-END:variables
}
