/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Painel_Doador;

import javax.swing.JOptionPane;

/**
 *
 * @author Tiago Cunha
 */
public class Inserir_Doador extends javax.swing.JPanel {

    /**
     * Creates new form Inserir_Doador
     */
    public Inserir_Doador() {
        initComponents();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        Nome = new javax.swing.JFormattedTextField();
        Niss = new javax.swing.JFormattedTextField();
        Nacionalidade = new javax.swing.JFormattedTextField();
        Telemovel = new javax.swing.JFormattedTextField();
        Email = new javax.swing.JFormattedTextField();
        Nif = new javax.swing.JFormattedTextField();
        Telefone = new javax.swing.JFormattedTextField();
        Feminino = new javax.swing.JCheckBox();
        Masculino = new javax.swing.JCheckBox();
        Camara = new javax.swing.JCheckBox();
        Privado = new javax.swing.JCheckBox();
        Empresa = new javax.swing.JCheckBox();
        gravar_Doador = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(null);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Nome");
        add(jLabel7);
        jLabel7.setBounds(170, 160, 70, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("NISS");
        add(jLabel8);
        jLabel8.setBounds(170, 210, 70, 17);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Nacionalidade");
        add(jLabel9);
        jLabel9.setBounds(170, 250, 90, 14);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Telemóvel ");
        add(jLabel11);
        jLabel11.setBounds(170, 370, 120, 30);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("E-mail");
        add(jLabel12);
        jLabel12.setBounds(170, 410, 110, 30);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("NIF");
        add(jLabel13);
        jLabel13.setBounds(460, 200, 30, 30);

        jLabel48.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel48.setText("Género");
        add(jLabel48);
        jLabel48.setBounds(170, 300, 60, 30);

        jLabel78.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel78.setText("Telefone");
        add(jLabel78);
        jLabel78.setBounds(430, 370, 70, 30);

        Nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomeActionPerformed(evt);
            }
        });
        add(Nome);
        Nome.setBounds(260, 160, 380, 30);
        add(Niss);
        Niss.setBounds(260, 200, 150, 30);
        add(Nacionalidade);
        Nacionalidade.setBounds(260, 240, 380, 30);
        add(Telemovel);
        Telemovel.setBounds(260, 370, 140, 30);
        add(Email);
        Email.setBounds(260, 410, 380, 30);
        add(Nif);
        Nif.setBounds(500, 200, 140, 30);
        add(Telefone);
        Telefone.setBounds(500, 370, 140, 30);

        Feminino.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Feminino.setText("Feminino");
        Feminino.setOpaque(false);
        Feminino.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                FemininoStateChanged(evt);
            }
        });
        Feminino.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FemininoMouseClicked(evt);
            }
        });
        Feminino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FemininoActionPerformed(evt);
            }
        });
        add(Feminino);
        Feminino.setBounds(260, 280, 110, 30);

        Masculino.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Masculino.setText("Masculino");
        Masculino.setOpaque(false);
        Masculino.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MasculinoMouseClicked(evt);
            }
        });
        add(Masculino);
        Masculino.setBounds(260, 320, 110, 30);

        Camara.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Camara.setText("Câmara");
        Camara.setOpaque(false);
        Camara.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CamaraMouseClicked(evt);
            }
        });
        add(Camara);
        Camara.setBounds(510, 270, 110, 30);

        Privado.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Privado.setText("Privado");
        Privado.setOpaque(false);
        Privado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PrivadoMouseClicked(evt);
            }
        });
        add(Privado);
        Privado.setBounds(510, 300, 110, 30);

        Empresa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Empresa.setText("Empresa");
        Empresa.setOpaque(false);
        Empresa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EmpresaMouseClicked(evt);
            }
        });
        add(Empresa);
        Empresa.setBounds(510, 330, 110, 30);

        gravar_Doador.setText("Inserir");
        gravar_Doador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gravar_DoadorMouseClicked(evt);
            }
        });
        gravar_Doador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gravar_DoadorActionPerformed(evt);
            }
        });
        add(gravar_Doador);
        gravar_Doador.setBounds(690, 490, 80, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Tipo");
        add(jLabel2);
        jLabel2.setBounds(460, 300, 50, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/987.jpg"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(0, 0, 954, 608);
    }// </editor-fold>//GEN-END:initComponents

    private void NomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NomeActionPerformed

    private void FemininoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_FemininoStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_FemininoStateChanged

    private void FemininoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FemininoMouseClicked
        // TODO add your handling code here:
        if(Feminino.isSelected()){
            Masculino.setEnabled(false);
        }else{
            Masculino.setEnabled(true);
        }
    }//GEN-LAST:event_FemininoMouseClicked

    private void FemininoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FemininoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FemininoActionPerformed

    private void MasculinoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MasculinoMouseClicked
        // TODO add your handling code here:
        if(Masculino.isSelected()){
            Feminino.setEnabled(false);
        }else{
            Feminino.setEnabled(true);
        }
    }//GEN-LAST:event_MasculinoMouseClicked

    private void gravar_DoadorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gravar_DoadorMouseClicked
        // TODO add your handling code here:
        if (this.Niss.getText().equals("") || this.Nome.getText().equals("") || this.Nacionalidade.getText().equals("") || this.Telefone.getText().equals("") || this.Nif.getText().equals("") ||
            this.Telemovel.getText().equals("") || this.Email.getText().equals("") || (!this.Feminino.isSelected() && !this.Masculino.isSelected()) || (!this.Camara.isSelected() && !this.Privado.isSelected() && !this.Empresa.isSelected()) ) {
            JOptionPane.showMessageDialog(null, "Preencha todos os campos!");
        }else{
            JOptionPane.showMessageDialog(null, "Inserido!");
            this.Niss.setText("");
            this.Nome.setText("");
            this.Nacionalidade.setText("");
            this.Telefone.setText("");
            this.Nif.setText("");
            this.Telemovel.setText("");
            this.Email.setText("");  
            this.Feminino.setSelected(false);
            this.Masculino.setSelected(false);
            this.Camara.setSelected(false);
            this.Privado.setSelected(false);
            this.Empresa.setSelected(false);
        }
    }//GEN-LAST:event_gravar_DoadorMouseClicked

    private void CamaraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CamaraMouseClicked
        // TODO add your handling code here:
        if(Camara.isSelected()){
            Privado.setEnabled(false);
            Empresa.setEnabled(false);
        }else{
            Privado.setEnabled(true);
            Empresa.setEnabled(true);
        }
    }//GEN-LAST:event_CamaraMouseClicked

    private void PrivadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PrivadoMouseClicked
        // TODO add your handling code here:
        if(Privado.isSelected()){
            Camara.setEnabled(false);
            Empresa.setEnabled(false);
        }else{
            Camara.setEnabled(true);
            Empresa.setEnabled(true);
        }
    }//GEN-LAST:event_PrivadoMouseClicked

    private void EmpresaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmpresaMouseClicked
        // TODO add your handling code here:
        if(Empresa.isSelected()){
            Privado.setEnabled(false);
            Camara.setEnabled(false);
        }else{
            Privado.setEnabled(true);
            Camara.setEnabled(true);
        }
    }//GEN-LAST:event_EmpresaMouseClicked

    private void gravar_DoadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gravar_DoadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gravar_DoadorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Camara;
    private javax.swing.JFormattedTextField Email;
    private javax.swing.JCheckBox Empresa;
    private javax.swing.JCheckBox Feminino;
    private javax.swing.JCheckBox Masculino;
    private javax.swing.JFormattedTextField Nacionalidade;
    private javax.swing.JFormattedTextField Nif;
    private javax.swing.JFormattedTextField Niss;
    private javax.swing.JFormattedTextField Nome;
    private javax.swing.JCheckBox Privado;
    private javax.swing.JFormattedTextField Telefone;
    private javax.swing.JFormattedTextField Telemovel;
    private javax.swing.JButton gravar_Doador;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
