/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Painel_Doador;

import javax.swing.JOptionPane;

/**
 *
 * @author Tiago Cunha
 */
public class Remover_Consultar_Doador extends javax.swing.JPanel {

    /**
     * Creates new form Remover_Consultar_Doador
     */
    public Remover_Consultar_Doador() {
        initComponents();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Nome = new javax.swing.JFormattedTextField();
        Niss = new javax.swing.JFormattedTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Nacionalidade = new javax.swing.JFormattedTextField();
        Nif = new javax.swing.JFormattedTextField();
        Camara = new javax.swing.JCheckBox();
        Telefone = new javax.swing.JFormattedTextField();
        Email = new javax.swing.JFormattedTextField();
        Feminino = new javax.swing.JCheckBox();
        jLabel12 = new javax.swing.JLabel();
        Empresa = new javax.swing.JCheckBox();
        Masculino = new javax.swing.JCheckBox();
        Privado = new javax.swing.JCheckBox();
        Telemovel = new javax.swing.JFormattedTextField();
        jLabel48 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Doadores = new javax.swing.JList();
        Remover = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(null);

        Nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomeActionPerformed(evt);
            }
        });
        add(Nome);
        Nome.setBounds(370, 160, 380, 30);
        add(Niss);
        Niss.setBounds(370, 200, 150, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Telemóvel ");
        add(jLabel11);
        jLabel11.setBounds(280, 370, 120, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Tipo");
        add(jLabel2);
        jLabel2.setBounds(570, 300, 50, 30);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("NIF");
        add(jLabel13);
        jLabel13.setBounds(570, 200, 30, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("NISS");
        add(jLabel8);
        jLabel8.setBounds(280, 210, 70, 17);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Nacionalidade");
        add(jLabel9);
        jLabel9.setBounds(280, 250, 90, 14);

        jLabel78.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel78.setText("Telefone");
        add(jLabel78);
        jLabel78.setBounds(540, 370, 70, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Nome");
        add(jLabel7);
        jLabel7.setBounds(280, 160, 70, 30);
        add(Nacionalidade);
        Nacionalidade.setBounds(370, 240, 380, 30);
        add(Nif);
        Nif.setBounds(610, 200, 140, 30);

        Camara.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Camara.setText("Câmara");
        Camara.setOpaque(false);
        Camara.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CamaraMouseClicked(evt);
            }
        });
        add(Camara);
        Camara.setBounds(620, 270, 110, 30);
        add(Telefone);
        Telefone.setBounds(610, 370, 140, 30);
        add(Email);
        Email.setBounds(370, 410, 380, 30);

        Feminino.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Feminino.setText("Feminino");
        Feminino.setOpaque(false);
        Feminino.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                FemininoStateChanged(evt);
            }
        });
        Feminino.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FemininoMouseClicked(evt);
            }
        });
        Feminino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FemininoActionPerformed(evt);
            }
        });
        add(Feminino);
        Feminino.setBounds(370, 280, 110, 30);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("E-mail");
        add(jLabel12);
        jLabel12.setBounds(280, 410, 110, 30);

        Empresa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Empresa.setText("Empresa");
        Empresa.setOpaque(false);
        Empresa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EmpresaMouseClicked(evt);
            }
        });
        add(Empresa);
        Empresa.setBounds(620, 330, 110, 30);

        Masculino.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Masculino.setText("Masculino");
        Masculino.setOpaque(false);
        Masculino.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MasculinoMouseClicked(evt);
            }
        });
        add(Masculino);
        Masculino.setBounds(370, 320, 110, 30);

        Privado.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Privado.setText("Privado");
        Privado.setOpaque(false);
        Privado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PrivadoMouseClicked(evt);
            }
        });
        add(Privado);
        Privado.setBounds(620, 300, 110, 30);
        add(Telemovel);
        Telemovel.setBounds(370, 370, 140, 30);

        jLabel48.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel48.setText("Género");
        add(jLabel48);
        jLabel48.setBounds(280, 300, 60, 30);

        Doadores.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(Doadores);

        add(jScrollPane1);
        jScrollPane1.setBounds(50, 160, 150, 300);

        Remover.setText("Remover");
        Remover.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RemoverMouseClicked(evt);
            }
        });
        Remover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoverActionPerformed(evt);
            }
        });
        add(Remover);
        Remover.setBounds(50, 480, 150, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/987.jpg"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(0, 0, 954, 608);
    }// </editor-fold>//GEN-END:initComponents

    private void NomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NomeActionPerformed

    private void CamaraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CamaraMouseClicked
        // TODO add your handling code here:
        if(Camara.isSelected()){
            Privado.setEnabled(false);
            Empresa.setEnabled(false);
        }else{
            Privado.setEnabled(true);
            Empresa.setEnabled(true);
        }
    }//GEN-LAST:event_CamaraMouseClicked

    private void FemininoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_FemininoStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_FemininoStateChanged

    private void FemininoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FemininoMouseClicked
        // TODO add your handling code here:
        if(Feminino.isSelected()){
            Masculino.setEnabled(false);
        }else{
            Masculino.setEnabled(true);
        }
    }//GEN-LAST:event_FemininoMouseClicked

    private void FemininoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FemininoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FemininoActionPerformed

    private void EmpresaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmpresaMouseClicked
        // TODO add your handling code here:
        if(Empresa.isSelected()){
            Privado.setEnabled(false);
            Camara.setEnabled(false);
        }else{
            Privado.setEnabled(true);
            Camara.setEnabled(true);
        }
    }//GEN-LAST:event_EmpresaMouseClicked

    private void MasculinoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MasculinoMouseClicked
        // TODO add your handling code here:
        if(Masculino.isSelected()){
            Feminino.setEnabled(false);
        }else{
            Feminino.setEnabled(true);
        }
    }//GEN-LAST:event_MasculinoMouseClicked

    private void PrivadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PrivadoMouseClicked
        // TODO add your handling code here:
        if(Privado.isSelected()){
            Camara.setEnabled(false);
            Empresa.setEnabled(false);
        }else{
            Camara.setEnabled(true);
            Empresa.setEnabled(true);
        }
    }//GEN-LAST:event_PrivadoMouseClicked

    private void RemoverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RemoverMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Removido!");
    }//GEN-LAST:event_RemoverMouseClicked

    private void RemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RemoverActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Camara;
    private javax.swing.JList Doadores;
    private javax.swing.JFormattedTextField Email;
    private javax.swing.JCheckBox Empresa;
    private javax.swing.JCheckBox Feminino;
    private javax.swing.JCheckBox Masculino;
    private javax.swing.JFormattedTextField Nacionalidade;
    private javax.swing.JFormattedTextField Nif;
    private javax.swing.JFormattedTextField Niss;
    private javax.swing.JFormattedTextField Nome;
    private javax.swing.JCheckBox Privado;
    private javax.swing.JButton Remover;
    private javax.swing.JFormattedTextField Telefone;
    private javax.swing.JFormattedTextField Telemovel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
