/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Painel_Administrador;

import javax.swing.JOptionPane;

/**
 *
 * @author Tiago Cunha
 */
public class Remover_Consultar_Funcionario extends javax.swing.JPanel {

    /**
     * Creates new form Remover_Consultar_Funcionario
     */
    public Remover_Consultar_Funcionario() {
        initComponents();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel34 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        Nome = new javax.swing.JFormattedTextField();
        Dia = new javax.swing.JFormattedTextField();
        Mes = new javax.swing.JFormattedTextField();
        Ano = new javax.swing.JFormattedTextField();
        Nacionalidade = new javax.swing.JFormattedTextField();
        Niss = new javax.swing.JFormattedTextField();
        Feminino = new javax.swing.JCheckBox();
        Masculino = new javax.swing.JCheckBox();
        Salario = new javax.swing.JFormattedTextField();
        Nif = new javax.swing.JFormattedTextField();
        Telefone = new javax.swing.JFormattedTextField();
        Telemovel = new javax.swing.JFormattedTextField();
        Morada = new javax.swing.JFormattedTextField();
        Cod_Postal = new javax.swing.JFormattedTextField();
        Localidade = new javax.swing.JFormattedTextField();
        Email = new javax.swing.JFormattedTextField();
        Comissao = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Lista = new javax.swing.JList();
        Remover = new javax.swing.JButton();
        Fundo_Remover_Funcionario = new javax.swing.JLabel();

        setLayout(null);

        jLabel34.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel34.setText("Nome");
        add(jLabel34);
        jLabel34.setBounds(280, 120, 50, 30);

        jLabel36.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel36.setText("Data de nascimento");
        add(jLabel36);
        jLabel36.setBounds(280, 160, 130, 30);

        jLabel42.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel42.setText("Nacionalidade");
        add(jLabel42);
        jLabel42.setBounds(570, 160, 90, 30);

        jLabel41.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel41.setText("NISS");
        add(jLabel41);
        jLabel41.setBounds(610, 200, 29, 30);

        jLabel43.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel43.setText("Sexo");
        add(jLabel43);
        jLabel43.setBounds(620, 250, 50, 30);

        jLabel75.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel75.setText("€");
        add(jLabel75);
        jLabel75.setBounds(590, 250, 8, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Salário");
        add(jLabel2);
        jLabel2.setBounds(480, 250, 60, 30);

        jLabel40.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel40.setText("NIF");
        add(jLabel40);
        jLabel40.setBounds(480, 200, 30, 30);

        jLabel35.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel35.setText("Telemóvel");
        add(jLabel35);
        jLabel35.setBounds(280, 250, 80, 30);

        jLabel44.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel44.setText("Telefone");
        add(jLabel44);
        jLabel44.setBounds(280, 200, 70, 30);

        jLabel38.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel38.setText("Morada");
        add(jLabel38);
        jLabel38.setBounds(280, 290, 70, 30);

        jLabel37.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel37.setText("Código-Postal");
        add(jLabel37);
        jLabel37.setBounds(370, 330, 100, 30);

        jLabel39.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel39.setText("Localidade");
        add(jLabel39);
        jLabel39.setBounds(580, 330, 100, 30);

        jLabel46.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel46.setText("Comissão");
        add(jLabel46);
        jLabel46.setBounds(280, 410, 90, 30);

        jLabel45.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel45.setText("E-mail");
        add(jLabel45);
        jLabel45.setBounds(280, 370, 70, 30);
        add(Nome);
        Nome.setBounds(370, 120, 380, 30);
        add(Dia);
        Dia.setBounds(410, 160, 40, 30);
        add(Mes);
        Mes.setBounds(460, 160, 40, 30);
        add(Ano);
        Ano.setBounds(510, 160, 40, 30);
        add(Nacionalidade);
        Nacionalidade.setBounds(660, 160, 90, 30);
        add(Niss);
        Niss.setBounds(650, 200, 100, 30);

        Feminino.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Feminino.setText("Feminino");
        Feminino.setOpaque(false);
        Feminino.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FemininoMouseClicked(evt);
            }
        });
        add(Feminino);
        Feminino.setBounds(670, 230, 90, 30);

        Masculino.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Masculino.setText("Masculino");
        Masculino.setOpaque(false);
        Masculino.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MasculinoMouseClicked(evt);
            }
        });
        add(Masculino);
        Masculino.setBounds(670, 260, 100, 30);
        add(Salario);
        Salario.setBounds(530, 250, 60, 30);
        add(Nif);
        Nif.setBounds(510, 200, 90, 30);
        add(Telefone);
        Telefone.setBounds(370, 200, 100, 30);
        add(Telemovel);
        Telemovel.setBounds(370, 250, 100, 30);
        add(Morada);
        Morada.setBounds(370, 290, 380, 30);
        add(Cod_Postal);
        Cod_Postal.setBounds(460, 330, 110, 30);
        add(Localidade);
        Localidade.setBounds(650, 330, 100, 30);
        add(Email);
        Email.setBounds(370, 370, 380, 30);
        add(Comissao);
        Comissao.setBounds(370, 410, 380, 30);

        Lista.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5", "Item 1", "Item 2", "Item 3", "Item 4", "Item 5", "Item 1", "Item 2", "Item 3", "Item 4", "Item 5", "Item 1", "Item 2", "Item 3", "Item 4", "Item 5", "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(Lista);

        add(jScrollPane1);
        jScrollPane1.setBounds(40, 120, 130, 310);

        Remover.setText("Remover");
        Remover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoverActionPerformed(evt);
            }
        });
        add(Remover);
        Remover.setBounds(40, 440, 130, 30);

        Fundo_Remover_Funcionario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Fundo_Remover_Funcionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/987.jpg"))); // NOI18N
        add(Fundo_Remover_Funcionario);
        Fundo_Remover_Funcionario.setBounds(0, 0, 960, 610);
    }// </editor-fold>//GEN-END:initComponents

    private void FemininoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FemininoMouseClicked
        // TODO add your handling code here:
        if(Feminino.isSelected()){
            Masculino.setEnabled(false);
        }else{
            Masculino.setEnabled(true);;
        }
    }//GEN-LAST:event_FemininoMouseClicked

    private void MasculinoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MasculinoMouseClicked
        // TODO add your handling code here:
        if(Masculino.isSelected()){
            Feminino.setEnabled(false);
        }else{
            Feminino.setEnabled(true);;
        }
    }//GEN-LAST:event_MasculinoMouseClicked

    private void RemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoverActionPerformed
        // TODO add your handling code here:
        
        JOptionPane.showMessageDialog(null, "Removido!");
    }//GEN-LAST:event_RemoverActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField Ano;
    private javax.swing.JFormattedTextField Cod_Postal;
    private javax.swing.JFormattedTextField Comissao;
    private javax.swing.JFormattedTextField Dia;
    private javax.swing.JFormattedTextField Email;
    private javax.swing.JCheckBox Feminino;
    private javax.swing.JLabel Fundo_Remover_Funcionario;
    private javax.swing.JList Lista;
    private javax.swing.JFormattedTextField Localidade;
    private javax.swing.JCheckBox Masculino;
    private javax.swing.JFormattedTextField Mes;
    private javax.swing.JFormattedTextField Morada;
    private javax.swing.JFormattedTextField Nacionalidade;
    private javax.swing.JFormattedTextField Nif;
    private javax.swing.JFormattedTextField Niss;
    private javax.swing.JFormattedTextField Nome;
    private javax.swing.JButton Remover;
    private javax.swing.JFormattedTextField Salario;
    private javax.swing.JFormattedTextField Telefone;
    private javax.swing.JFormattedTextField Telemovel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
