/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Painel_Projecto;

import javax.swing.JOptionPane;

/**
 *
 * @author Tiago Cunha
 */
public class Inserir_Projecto extends javax.swing.JPanel {

    /**
     * Creates new form Inserir_Projecto
     */
    public Inserir_Projecto() {
        initComponents();
        this.setVisible(true);        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel74 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        jLabel81 = new javax.swing.JLabel();
        Dia = new javax.swing.JFormattedTextField();
        Niss = new javax.swing.JFormattedTextField();
        Prazo = new javax.swing.JFormattedTextField();
        Mes = new javax.swing.JFormattedTextField();
        Ano = new javax.swing.JFormattedTextField();
        jButton4 = new javax.swing.JButton();
        Familia = new javax.swing.JComboBox();
        Candidatura = new javax.swing.JComboBox();
        jLabel22 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(null);

        jLabel74.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel74.setText("Responsável (NISS)");
        add(jLabel74);
        jLabel74.setBounds(440, 180, 130, 30);

        jLabel76.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel76.setText("Data");
        add(jLabel76);
        jLabel76.setBounds(440, 230, 60, 30);

        jLabel77.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel77.setText("Prazo");
        add(jLabel77);
        jLabel77.setBounds(440, 290, 34, 30);

        jLabel81.setText("Dias");
        add(jLabel81);
        jLabel81.setBounds(630, 290, 40, 30);
        add(Dia);
        Dia.setBounds(570, 230, 40, 30);
        add(Niss);
        Niss.setBounds(570, 180, 140, 30);
        add(Prazo);
        Prazo.setBounds(570, 290, 50, 30);
        add(Mes);
        Mes.setBounds(620, 230, 40, 30);
        add(Ano);
        Ano.setBounds(670, 230, 40, 30);

        jButton4.setText("Inserir");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        add(jButton4);
        jButton4.setBounds(630, 450, 80, 30);

        Familia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Familia", "Item 2", "Item 3", "Item 4" }));
        add(Familia);
        Familia.setBounds(20, 180, 150, 30);

        Candidatura.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Candidatura", "Item 2", "Item 3", "Item 4" }));
        add(Candidatura);
        Candidatura.setBounds(210, 180, 150, 30);

        jLabel22.setText("  (dd-mm-aaaa)  ");
        add(jLabel22);
        jLabel22.setBounds(600, 260, 80, 14);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/987.jpg"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(0, 0, 954, 608);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
        if (this.Niss.getText().equals("") || this.Dia.getText().equals("") || this.Mes.getText().equals("") || this.Ano.getText().equals("") || 
            this.Prazo.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencha todos os campos!");
        }else{
            JOptionPane.showMessageDialog(null, "Inserido!");
            this.Niss.setText("");
            this.Dia.setText("");
            this.Mes.setText("");
            this.Ano.setText("");
            this.Prazo.setText("");
        }
    }//GEN-LAST:event_jButton4MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField Ano;
    private javax.swing.JComboBox Candidatura;
    private javax.swing.JFormattedTextField Dia;
    private javax.swing.JComboBox Familia;
    private javax.swing.JFormattedTextField Mes;
    private javax.swing.JFormattedTextField Niss;
    private javax.swing.JFormattedTextField Prazo;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel81;
    // End of variables declaration//GEN-END:variables
}
