/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Painel_Projecto;

import javax.swing.JOptionPane;

/**
 *
 * @author Tiago Cunha
 */
public class Remover_Consultar_Projectos extends javax.swing.JPanel {

    /**
     * Creates new form Remover_Consultar_Projectos
     */
    public Remover_Consultar_Projectos() {
        initComponents();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Niss = new javax.swing.JFormattedTextField();
        Dia_Inicial = new javax.swing.JFormattedTextField();
        Mes_Inicial = new javax.swing.JFormattedTextField();
        Ano_Inicial = new javax.swing.JFormattedTextField();
        Prazo = new javax.swing.JFormattedTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        jLabel79 = new javax.swing.JLabel();
        jLabel81 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Projectos = new javax.swing.JList();
        Remover = new javax.swing.JButton();
        Dia_Final = new javax.swing.JFormattedTextField();
        Mes_Final = new javax.swing.JFormattedTextField();
        Ano_Final = new javax.swing.JFormattedTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(null);
        add(Niss);
        Niss.setBounds(570, 180, 140, 30);
        add(Dia_Inicial);
        Dia_Inicial.setBounds(570, 230, 40, 30);
        add(Mes_Inicial);
        Mes_Inicial.setBounds(620, 230, 40, 30);
        add(Ano_Inicial);
        Ano_Inicial.setBounds(670, 230, 40, 30);
        add(Prazo);
        Prazo.setBounds(570, 350, 40, 30);

        jLabel22.setText("  (dd-mm-aaaa)  ");
        add(jLabel22);
        jLabel22.setBounds(600, 260, 80, 14);

        jLabel74.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel74.setText("Responsável (NISS)");
        add(jLabel74);
        jLabel74.setBounds(440, 180, 130, 30);

        jLabel76.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel76.setText("Data Inicial");
        add(jLabel76);
        jLabel76.setBounds(440, 230, 90, 30);

        jLabel77.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel77.setText("Prazo");
        add(jLabel77);
        jLabel77.setBounds(440, 350, 34, 30);

        jLabel78.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel78.setText("Data Inicial");
        add(jLabel78);
        jLabel78.setBounds(440, 230, 90, 30);

        jLabel79.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel79.setText("Data Final");
        add(jLabel79);
        jLabel79.setBounds(440, 290, 90, 30);

        jLabel81.setText("Dias");
        add(jLabel81);
        jLabel81.setBounds(630, 350, 40, 30);

        Projectos.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5", "Item 1", "Item 2", "Item 3", "Item 4", "Item 5", "Item 1", "Item 2", "Item 3", "Item 4", "Item 5", "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(Projectos);

        add(jScrollPane1);
        jScrollPane1.setBounds(90, 160, 140, 260);

        Remover.setText("Remover");
        Remover.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RemoverMouseClicked(evt);
            }
        });
        add(Remover);
        Remover.setBounds(90, 443, 140, 30);
        add(Dia_Final);
        Dia_Final.setBounds(570, 290, 40, 30);
        add(Mes_Final);
        Mes_Final.setBounds(620, 290, 40, 30);
        add(Ano_Final);
        Ano_Final.setBounds(670, 290, 40, 30);

        jLabel24.setText("  (dd-mm-aaaa)  ");
        add(jLabel24);
        jLabel24.setBounds(600, 320, 80, 14);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/987.jpg"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(0, 0, 954, 608);
    }// </editor-fold>//GEN-END:initComponents

    private void RemoverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RemoverMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Removido com Sucesso!");
    }//GEN-LAST:event_RemoverMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField Ano_Final;
    private javax.swing.JFormattedTextField Ano_Inicial;
    private javax.swing.JFormattedTextField Dia_Final;
    private javax.swing.JFormattedTextField Dia_Inicial;
    private javax.swing.JFormattedTextField Mes_Final;
    private javax.swing.JFormattedTextField Mes_Inicial;
    private javax.swing.JFormattedTextField Niss;
    private javax.swing.JFormattedTextField Prazo;
    private javax.swing.JList Projectos;
    private javax.swing.JButton Remover;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
