/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Painel_Candidatura;

import javax.swing.JOptionPane;

/**
 *
 * @author Tiago Cunha
 */
public class Inserir_Candidatura extends javax.swing.JPanel {

    /**
     * Creates new form Inserir_Candidatura
     */
    public Inserir_Candidatura() {
        initComponents();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel25 = new javax.swing.JLabel();
        Mes = new javax.swing.JFormattedTextField();
        Ano = new javax.swing.JFormattedTextField();
        jLabel27 = new javax.swing.JLabel();
        Dia = new javax.swing.JFormattedTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        Inserir = new javax.swing.JButton();
        Lista_Familias = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        Observacoes = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        Documentos = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setLayout(null);

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel25.setText("Data Submissão");
        add(jLabel25);
        jLabel25.setBounds(250, 160, 110, 30);
        add(Mes);
        Mes.setBounds(430, 160, 40, 30);
        add(Ano);
        Ano.setBounds(480, 160, 40, 30);

        jLabel27.setText("(dd-mm-aaaa)");
        add(jLabel27);
        jLabel27.setBounds(540, 160, 100, 30);
        add(Dia);
        Dia.setBounds(380, 160, 40, 30);

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel24.setText("Observações:");
        add(jLabel24);
        jLabel24.setBounds(250, 280, 110, 30);

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel26.setText("Nome Documentos:");
        add(jLabel26);
        jLabel26.setBounds(250, 400, 130, 30);

        Inserir.setText("Inserir");
        Inserir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InserirMouseClicked(evt);
            }
        });
        add(Inserir);
        Inserir.setBounds(740, 500, 80, 30);

        Lista_Familias.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Familia", "Item 2", "Item 3", "Item 4" }));
        add(Lista_Familias);
        Lista_Familias.setBounds(380, 220, 120, 30);

        Observacoes.setColumns(20);
        Observacoes.setRows(5);
        jScrollPane1.setViewportView(Observacoes);

        add(jScrollPane1);
        jScrollPane1.setBounds(380, 280, 310, 96);

        Documentos.setColumns(20);
        Documentos.setRows(5);
        jScrollPane2.setViewportView(Documentos);

        add(jScrollPane2);
        jScrollPane2.setBounds(380, 410, 310, 96);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/987.jpg"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(0, 0, 960, 610);
    }// </editor-fold>//GEN-END:initComponents

    private void InserirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InserirMouseClicked
        // TODO add your handling code here:
       if (this.Observacoes.getText().equals("") || this.Dia.getText().equals("") || this.Mes.getText().equals("") || this.Ano.getText().equals("") || 
            this.Documentos.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencha todos os campos!");
        }else{
            JOptionPane.showMessageDialog(null, "Inserido!");
            this.Observacoes.setText("");
            this.Dia.setText("");
            this.Mes.setText("");
            this.Ano.setText("");
            this.Documentos.setText("");            
        }
    }//GEN-LAST:event_InserirMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField Ano;
    private javax.swing.JFormattedTextField Dia;
    private javax.swing.JTextArea Documentos;
    private javax.swing.JButton Inserir;
    private javax.swing.JComboBox Lista_Familias;
    private javax.swing.JFormattedTextField Mes;
    private javax.swing.JTextArea Observacoes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
