/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Painel_Familia;

import javax.swing.JOptionPane;

/**
 *
 * @author Tiago Cunha
 */
public class Inserir_Familia extends javax.swing.JPanel {

    /**
     * Creates new form Inserir_Famili
     */
    public Inserir_Familia() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel34 = new javax.swing.JLabel();
        Rendimento = new javax.swing.JFormattedTextField();
        jLabel38 = new javax.swing.JLabel();
        Morada = new javax.swing.JFormattedTextField();
        jLabel37 = new javax.swing.JLabel();
        Cod_Postal = new javax.swing.JFormattedTextField();
        jLabel39 = new javax.swing.JLabel();
        Localidade = new javax.swing.JFormattedTextField();
        jLabel75 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Nelementos = new javax.swing.JFormattedTextField();
        Inserir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(null);

        jLabel34.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel34.setText("Rendimento");
        add(jLabel34);
        jLabel34.setBounds(260, 170, 90, 30);
        add(Rendimento);
        Rendimento.setBounds(350, 170, 40, 30);

        jLabel38.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel38.setText("Morada");
        add(jLabel38);
        jLabel38.setBounds(260, 230, 70, 30);
        add(Morada);
        Morada.setBounds(350, 230, 380, 30);

        jLabel37.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel37.setText("Código-Postal");
        add(jLabel37);
        jLabel37.setBounds(350, 270, 100, 30);
        add(Cod_Postal);
        Cod_Postal.setBounds(440, 270, 110, 30);

        jLabel39.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel39.setText("Localidade");
        add(jLabel39);
        jLabel39.setBounds(560, 270, 100, 30);
        add(Localidade);
        Localidade.setBounds(630, 270, 100, 30);

        jLabel75.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel75.setText("€");
        add(jLabel75);
        jLabel75.setBounds(400, 170, 8, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Nº Elementos");
        add(jLabel2);
        jLabel2.setBounds(470, 170, 100, 30);
        add(Nelementos);
        Nelementos.setBounds(590, 170, 50, 30);

        Inserir.setText("Inserir");
        Inserir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InserirMouseClicked(evt);
            }
        });
        Inserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InserirActionPerformed(evt);
            }
        });
        add(Inserir);
        Inserir.setBounds(750, 490, 80, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/987.jpg"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(0, 0, 954, 608);
    }// </editor-fold>//GEN-END:initComponents

    private void InserirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InserirMouseClicked
        // TODO add your handling code here:
        if (this.Rendimento.getText().equals("") || this.Nelementos.getText().equals("") || this.Cod_Postal.getText().equals("") || this.Morada.getText().equals("") || this.Localidade.getText().equals("") ) {
            JOptionPane.showMessageDialog(null, "Preencha todos os campos!");
        }else{
            JOptionPane.showMessageDialog(null, "Inserido!");
            this.Rendimento.setText("");
            this.Nelementos.setText("");
            this.Morada.setText("");
            this.Localidade.setText("");
            this.Cod_Postal.setText("");
        }
    }//GEN-LAST:event_InserirMouseClicked

    private void InserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InserirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InserirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField Cod_Postal;
    private javax.swing.JButton Inserir;
    private javax.swing.JFormattedTextField Localidade;
    private javax.swing.JFormattedTextField Morada;
    private javax.swing.JFormattedTextField Nelementos;
    private javax.swing.JFormattedTextField Rendimento;
    private javax.swing.JButton gravar_Doador;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel75;
    // End of variables declaration//GEN-END:variables
}
