/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Painel_Familia;

import javax.swing.JOptionPane;

/**
 *
 * @author Tiago Cunha
 */
public class Membro_Familia extends javax.swing.JPanel {

    /**
     * Creates new form Membro_familia
     */
    public Membro_Familia() {
        initComponents();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel34 = new javax.swing.JLabel();
        Nome = new javax.swing.JFormattedTextField();
        Dia = new javax.swing.JFormattedTextField();
        Mes = new javax.swing.JFormattedTextField();
        Ano = new javax.swing.JFormattedTextField();
        jLabel42 = new javax.swing.JLabel();
        Rendimento = new javax.swing.JFormattedTextField();
        Niss = new javax.swing.JFormattedTextField();
        jLabel41 = new javax.swing.JLabel();
        Nif = new javax.swing.JFormattedTextField();
        jLabel40 = new javax.swing.JLabel();
        Telefone = new javax.swing.JFormattedTextField();
        jLabel44 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        Profissao = new javax.swing.JFormattedTextField();
        jLabel43 = new javax.swing.JLabel();
        Feminino = new javax.swing.JCheckBox();
        Masculino = new javax.swing.JCheckBox();
        Inserir = new javax.swing.JButton();
        jLabel75 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        Representante = new javax.swing.JCheckBox();
        Nao_Representante = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();

        setLayout(null);

        jLabel34.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel34.setText("Nome");
        add(jLabel34);
        jLabel34.setBounds(230, 200, 50, 30);
        add(Nome);
        Nome.setBounds(320, 200, 380, 30);
        add(Dia);
        Dia.setBounds(360, 250, 40, 30);
        add(Mes);
        Mes.setBounds(410, 250, 40, 30);
        add(Ano);
        Ano.setBounds(460, 250, 40, 30);

        jLabel42.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel42.setText("Rendimento");
        add(jLabel42);
        jLabel42.setBounds(520, 250, 80, 30);
        add(Rendimento);
        Rendimento.setBounds(610, 250, 50, 30);
        add(Niss);
        Niss.setBounds(600, 300, 100, 30);

        jLabel41.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel41.setText("NISS");
        add(jLabel41);
        jLabel41.setBounds(560, 300, 29, 30);
        add(Nif);
        Nif.setBounds(460, 300, 90, 30);

        jLabel40.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel40.setText("NIF");
        add(jLabel40);
        jLabel40.setBounds(430, 300, 30, 30);
        add(Telefone);
        Telefone.setBounds(320, 300, 100, 30);

        jLabel44.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel44.setText("Telefone");
        add(jLabel44);
        jLabel44.setBounds(230, 300, 70, 30);

        jLabel36.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel36.setText("Data de nascimento");
        add(jLabel36);
        jLabel36.setBounds(230, 250, 130, 30);

        jLabel35.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel35.setText("Profissão");
        add(jLabel35);
        jLabel35.setBounds(230, 350, 60, 30);
        add(Profissao);
        Profissao.setBounds(320, 350, 380, 30);

        jLabel43.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel43.setText("Género");
        add(jLabel43);
        jLabel43.setBounds(470, 410, 50, 30);

        Feminino.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Feminino.setText("Feminino");
        Feminino.setOpaque(false);
        Feminino.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FemininoMouseClicked(evt);
            }
        });
        add(Feminino);
        Feminino.setBounds(530, 390, 90, 30);

        Masculino.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Masculino.setText("Masculino");
        Masculino.setOpaque(false);
        Masculino.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MasculinoMouseClicked(evt);
            }
        });
        add(Masculino);
        Masculino.setBounds(530, 430, 100, 30);

        Inserir.setText("Inserir");
        Inserir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InserirMouseClicked(evt);
            }
        });
        Inserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InserirActionPerformed(evt);
            }
        });
        add(Inserir);
        Inserir.setBounds(750, 490, 80, 30);

        jLabel75.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel75.setText("€");
        add(jLabel75);
        jLabel75.setBounds(670, 250, 20, 30);

        jLabel45.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel45.setText("Representante");
        add(jLabel45);
        jLabel45.setBounds(230, 410, 100, 30);

        Representante.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Representante.setText("Sim");
        Representante.setOpaque(false);
        Representante.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RepresentanteMouseClicked(evt);
            }
        });
        add(Representante);
        Representante.setBounds(320, 390, 90, 30);

        Nao_Representante.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Nao_Representante.setText("Não");
        Nao_Representante.setOpaque(false);
        Nao_Representante.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Nao_RepresentanteMouseClicked(evt);
            }
        });
        add(Nao_Representante);
        Nao_Representante.setBounds(320, 430, 100, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/987.jpg"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(0, 0, 954, 608);
    }// </editor-fold>//GEN-END:initComponents

    private void FemininoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FemininoMouseClicked
        // TODO add your handling code here:
        if(Feminino.isSelected()){
            Masculino.setEnabled(false);
        }else{
            Masculino.setEnabled(true);;
        }
    }//GEN-LAST:event_FemininoMouseClicked

    private void MasculinoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MasculinoMouseClicked
        // TODO add your handling code here:
        if(Masculino.isSelected()){
            Feminino.setEnabled(false);
        }else{
            Feminino.setEnabled(true);;
        }
    }//GEN-LAST:event_MasculinoMouseClicked

    private void InserirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InserirMouseClicked
        // TODO add your handling code here:
        if (this.Niss.getText().equals("") || this.Dia.getText().equals("") || this.Mes.getText().equals("") || this.Ano.getText().equals("") || 
            this.Nome.getText().equals("") || this.Rendimento.getText().equals("") || this.Telefone.getText().equals("") || this.Nif.getText().equals("") ||
            this.Profissao.getText().equals("") || (!this.Feminino.isSelected() && !this.Masculino.isSelected()) || (!this.Representante.isSelected() && !this.Nao_Representante.isSelected())) {
            JOptionPane.showMessageDialog(null, "Preencha todos os campos!");
        }else{
            JOptionPane.showMessageDialog(null, "Inserido!");
            this.Niss.setText("");
            this.Dia.setText("");
            this.Mes.setText("");
            this.Ano.setText("");
            this.Nome.setText("");
            this.Telefone.setText("");
            this.Rendimento.setText("");
            this.Nif.setText("");  
            this.Feminino.setSelected(false);
            this.Masculino.setSelected(false);
            this.Representante.setSelected(false);
            this.Nao_Representante.setSelected(false);
        }
    }//GEN-LAST:event_InserirMouseClicked

    private void InserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InserirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InserirActionPerformed

    private void RepresentanteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RepresentanteMouseClicked
        // TODO add your handling code here:
        if(Representante.isSelected()){
            Nao_Representante.setEnabled(false);
        }else{
            Nao_Representante.setEnabled(true);;
        }
    }//GEN-LAST:event_RepresentanteMouseClicked

    private void Nao_RepresentanteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Nao_RepresentanteMouseClicked
        // TODO add your handling code here:
        if(Nao_Representante.isSelected()){
            Representante.setEnabled(false);
        }else{
            Representante.setEnabled(true);;
        }
    }//GEN-LAST:event_Nao_RepresentanteMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField Ano;
    private javax.swing.JFormattedTextField Dia;
    private javax.swing.JCheckBox Feminino;
    private javax.swing.JButton Inserir;
    private javax.swing.JCheckBox Masculino;
    private javax.swing.JFormattedTextField Mes;
    private javax.swing.JCheckBox Nao_Representante;
    private javax.swing.JFormattedTextField Nif;
    private javax.swing.JFormattedTextField Niss;
    private javax.swing.JFormattedTextField Nome;
    private javax.swing.JFormattedTextField Profissao;
    private javax.swing.JFormattedTextField Rendimento;
    private javax.swing.JCheckBox Representante;
    private javax.swing.JFormattedTextField Telefone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel75;
    // End of variables declaration//GEN-END:variables
}
